version: '2'

services:
    app:
        image: php:8.0-fpm
        volumes:
            - .:/app
    composer:
        #docker-compose run --rm composer composer update --working-dir /app
        image: hq.attlaz.com:2498/php7_4:1.1.0
        volumes:
            - .:/app
    phpunit:
        image: php:7.4-cli
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: vendor/bin/phpunit
        #docker-compose run --rm phpunit -c /app/phpunit.xml

